use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::fmt;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum ThemeMode {
    Light,
    Dark,
}

impl fmt::Display for ThemeMode {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        match self {
            ThemeMode::Light => write!(f, "light"),
            ThemeMode::Dark => write!(f, "dark"),
        }
    }
}

impl std::str::FromStr for ThemeMode {
    type Err = crate::Error;
    
    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s.to_lowercase().as_str() {
            "light" => Ok(ThemeMode::Light),
            "dark" => Ok(ThemeMode::Dark),
            _ => Err(crate::Error::Config(format!("Invalid theme mode: {}", s))),
        }
    }
}

/// Material You color scheme
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ColorScheme {
    pub mode: ThemeMode,
    pub colors: HashMap<String, String>,
}

impl ColorScheme {
    pub fn new(mode: ThemeMode) -> Self {
        Self {
            mode,
            colors: HashMap::new(),
        }
    }
    
    pub fn get(&self, key: &str) -> Option<&String> {
        self.colors.get(key)
    }
    
    pub fn set(&mut self, key: String, value: String) {
        self.colors.insert(key, value);
    }
    
    /// Generate GTK CSS with @define-color declarations
    pub fn to_gtk_css(&self) -> String {
        let mut css = String::new();
        css.push_str("/* Material You colors generated by lmtt */\n");
        css.push_str(&format!("/* Mode: {} */\n\n", self.mode));
        
        for (key, value) in &self.colors {
            css.push_str(&format!("@define-color {} {};\n", key, value));
        }
        
        // Add compatibility aliases
        css.push_str("\n/* Compatibility aliases */\n");
        css.push_str("@define-color foreground @on_surface;\n");
        css.push_str("@define-color accent @primary;\n");
        css.push_str("@define-color color7 @on_surface;\n");
        css.push_str("@define-color color9 @secondary;\n");
        
        css
    }
    
    /// Get primary color
    pub fn primary(&self) -> Option<&String> {
        self.get("primary")
    }
    
    /// Get background color
    pub fn background(&self) -> Option<&String> {
        self.get("surface")
    }
}
