use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::fmt;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum ThemeMode {
    Light,
    Dark,
}

impl fmt::Display for ThemeMode {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        match self {
            ThemeMode::Light => write!(f, "light"),
            ThemeMode::Dark => write!(f, "dark"),
        }
    }
}

impl std::str::FromStr for ThemeMode {
    type Err = crate::Error;
    
    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s.to_lowercase().as_str() {
            "light" => Ok(ThemeMode::Light),
            "dark" => Ok(ThemeMode::Dark),
            _ => Err(crate::Error::Config(format!("Invalid theme mode: {}", s))),
        }
    }
}

/// Material You color scheme
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ColorScheme {
    pub mode: ThemeMode,
    pub colors: HashMap<String, String>,
}

impl ColorScheme {
    pub fn new(mode: ThemeMode) -> Self {
        Self {
            mode,
            colors: HashMap::new(),
        }
    }
    
    pub fn get(&self, key: &str) -> Option<&String> {
        self.colors.get(key)
    }
    
    pub fn set(&mut self, key: String, value: String) {
        self.colors.insert(key, value);
    }

    /// Get a color, falling back to the built-in palette for this mode.
    /// Neutral gray if the token exists in neither (never panics).
    pub fn get_or_fallback(&self, key: &str) -> String {
        if let Some(value) = self.colors.get(key) {
            return value.clone();
        }
        crate::fallback::fallback_color(self.mode, key)
            .map(|s| s.to_string())
            .unwrap_or_else(|| "#808080".to_string())
    }
    
    /// Generate GTK CSS with @define-color declarations
    pub fn to_gtk_css(&self) -> String {
        let mut css = String::new();
        css.push_str("/* Material You colors generated by lmtt */\n");
        css.push_str(&format!("/* Mode: {} */\n\n", self.mode));

        // Sorted so identical schemes produce byte-identical files —
        // file-watchers (waybar, wezterm) shouldn't reload on key order noise.
        let mut keys: Vec<_> = self.colors.keys().collect();
        keys.sort();
        for key in keys {
            css.push_str(&format!("@define-color {} {};\n", key, self.colors[key]));
        }

        // Compatibility aliases — only when the target exists (a dangling
        // @define-color reference breaks GTK's CSS parse) AND the alias name
        // isn't itself a user-supplied color (last @define-color wins, so an
        // unconditional alias would silently clobber an explicit override).
        css.push_str("\n/* Compatibility aliases */\n");
        for (alias, target) in [
            ("foreground", "on_surface"),
            ("accent", "primary"),
            ("color7", "on_surface"),
            ("color9", "secondary"),
        ] {
            if self.colors.contains_key(target) && !self.colors.contains_key(alias) {
                css.push_str(&format!("@define-color {} @{};\n", alias, target));
            }
        }

        css
    }
    
    /// Get primary color
    pub fn primary(&self) -> Option<&String> {
        self.get("primary")
    }
    
    /// Get background color
    pub fn background(&self) -> Option<&String> {
        self.get("surface")
    }
}
