use crate::{ConfigFileInfo, ThemeModule};
use async_trait::async_trait;
use lmtt_core::{ColorScheme, Config, Result};

crate::register_module!(FuzzelModule);

pub struct FuzzelModule;

impl Default for FuzzelModule {
    fn default() -> Self {
        Self::new()
    }
}

impl FuzzelModule {
    pub fn new() -> Self {
        Self
    }
}

/// Convert hex color to fuzzel format (rrggbbaa). Parse via hex_to_rgb
/// (byte-safe, handles #rgb / #rrggbb / #rrggbbaa), then append the alpha.
fn hex_to_fuzzel(hex: &str, alpha: &str) -> String {
    let (r, g, b) = lmtt_core::colors::hex_to_rgb(hex).unwrap_or((0, 0, 0));
    format!("{:02x}{:02x}{:02x}{}", r, g, b, alpha)
}

#[async_trait]
impl ThemeModule for FuzzelModule {
    fn name(&self) -> &'static str {
        "fuzzel"
    }

    fn binary_name(&self) -> &'static str {
        "fuzzel"
    }

    async fn apply(&self, scheme: &ColorScheme, _config: &Config) -> Result<()> {
        let config_dir = dirs::config_dir()
            .ok_or(lmtt_core::Error::Config("No config dir".into()))?;

        let fuzzel_dir = config_dir.join("fuzzel");
        let colors_file = fuzzel_dir.join("lmtt-colors.ini");

        // Ensure directory exists
        if let Some(parent) = colors_file.parent() {
            tokio::fs::create_dir_all(parent).await?;
        }

        // Colors from the scheme, with mode-appropriate canonical fallbacks
        let surface = scheme.get_or_fallback("surface");
        let on_surface = scheme.get_or_fallback("on_surface");
        let primary = scheme.get_or_fallback("primary");
        let outline = scheme.get_or_fallback("outline");
        let on_primary_container = scheme.get_or_fallback("on_primary_container");
        let primary_container = scheme.get_or_fallback("primary_container");

        // Build INI content
        // Fuzzel colors use rrggbbaa format (no # prefix, with alpha)
        let mut content = String::new();
        content.push_str("# Fuzzel colors generated by lmtt\n");
        content.push_str("# Include this in fuzzel.ini with: include=~/.config/fuzzel/lmtt-colors.ini\n\n");
        content.push_str("[colors]\n");
        content.push_str(&format!("background={}\n", hex_to_fuzzel(&surface, "ee")));
        content.push_str(&format!("text={}\n", hex_to_fuzzel(&on_surface, "ff")));
        content.push_str(&format!("prompt={}\n", hex_to_fuzzel(&primary, "ff")));
        content.push_str(&format!("placeholder={}\n", hex_to_fuzzel(&outline, "aa")));
        content.push_str(&format!("input={}\n", hex_to_fuzzel(&on_surface, "ff")));
        content.push_str(&format!("match={}\n", hex_to_fuzzel(&primary, "ff")));
        content.push_str(&format!(
            "selection={}\n",
            hex_to_fuzzel(&primary_container, "ff")
        ));
        content.push_str(&format!(
            "selection-text={}\n",
            hex_to_fuzzel(&on_primary_container, "ff")
        ));
        content.push_str(&format!(
            "selection-match={}\n",
            hex_to_fuzzel(&primary, "ff")
        ));
        content.push_str(&format!("counter={}\n", hex_to_fuzzel(&outline, "ff")));
        content.push_str(&format!("border={}\n", hex_to_fuzzel(&outline, "ff")));

        lmtt_core::fsutil::write_atomic(&colors_file, content).await?;

        tracing::info!("[Fuzzel] Updated colors at {}", colors_file.display());

        Ok(())
    }

    async fn config_files(&self) -> Result<Vec<ConfigFileInfo>> {
        let config_dir =
            dirs::config_dir().ok_or(lmtt_core::Error::Config("No config dir".into()))?;

        let fuzzel_ini = config_dir.join("fuzzel").join("fuzzel.ini");

        // If no fuzzel.ini exists, return empty (user needs to create one)
        if !fuzzel_ini.exists() {
            return Ok(vec![]);
        }

        let content = tokio::fs::read_to_string(&fuzzel_ini).await?;
        let include_line = "include=~/.config/fuzzel/lmtt-colors.ini";
        let already_included = crate::is_included(&content, include_line);

        Ok(vec![ConfigFileInfo {
            path: fuzzel_ini,
            include_line: include_line.to_string(),
            description: "Include lmtt colors into Fuzzel config".to_string(),
            already_included,
        }])
    }
}
