use crate::{ConfigFileInfo, ThemeModule};
use async_trait::async_trait;
use lmtt_core::{ColorScheme, Config, Result};

crate::register_module!(FuzzelModule);

pub struct FuzzelModule;

impl FuzzelModule {
    pub fn new() -> Self {
        Self
    }
}

/// Convert hex color (#rrggbb) to fuzzel format (rrggbbaa)
fn hex_to_fuzzel(hex: &str, alpha: &str) -> String {
    let hex = hex.trim_start_matches('#');
    format!("{}{}", hex, alpha)
}

#[async_trait]
impl ThemeModule for FuzzelModule {
    fn name(&self) -> &'static str {
        "fuzzel"
    }

    fn binary_name(&self) -> &'static str {
        "fuzzel"
    }

    async fn apply(&self, scheme: &ColorScheme, _config: &Config) -> Result<()> {
        let config_dir = dirs::config_dir()
            .ok_or(lmtt_core::Error::Config("No config dir".into()))?;

        let fuzzel_dir = config_dir.join("fuzzel");
        let colors_file = fuzzel_dir.join("lmtt-colors.ini");

        // Ensure directory exists
        if let Some(parent) = colors_file.parent() {
            tokio::fs::create_dir_all(parent).await?;
        }

        // Default colors (dark theme fallbacks)
        let default_surface = "#1e1f25".to_string();
        let default_on_surface = "#e3e1ec".to_string();
        let default_primary = "#9fd491".to_string();
        let default_outline = "#8f909f".to_string();
        let default_on_primary_container = "#d4ffcf".to_string();
        let default_primary_container = "#1d5120".to_string();

        // Get colors from scheme
        let surface = scheme.get("surface").unwrap_or(&default_surface);
        let on_surface = scheme.get("on_surface").unwrap_or(&default_on_surface);
        let primary = scheme.get("primary").unwrap_or(&default_primary);
        let outline = scheme.get("outline").unwrap_or(&default_outline);
        let on_primary_container = scheme
            .get("on_primary_container")
            .unwrap_or(&default_on_primary_container);
        let primary_container = scheme
            .get("primary_container")
            .unwrap_or(&default_primary_container);

        // Build INI content
        // Fuzzel colors use rrggbbaa format (no # prefix, with alpha)
        let mut content = String::new();
        content.push_str("# Fuzzel colors generated by lmtt\n");
        content.push_str("# Include this in fuzzel.ini with: include=~/.config/fuzzel/lmtt-colors.ini\n\n");
        content.push_str("[colors]\n");
        content.push_str(&format!("background={}\n", hex_to_fuzzel(surface, "ee")));
        content.push_str(&format!("text={}\n", hex_to_fuzzel(on_surface, "ff")));
        content.push_str(&format!("prompt={}\n", hex_to_fuzzel(primary, "ff")));
        content.push_str(&format!("placeholder={}\n", hex_to_fuzzel(outline, "aa")));
        content.push_str(&format!("input={}\n", hex_to_fuzzel(on_surface, "ff")));
        content.push_str(&format!("match={}\n", hex_to_fuzzel(primary, "ff")));
        content.push_str(&format!(
            "selection={}\n",
            hex_to_fuzzel(primary_container, "ff")
        ));
        content.push_str(&format!(
            "selection-text={}\n",
            hex_to_fuzzel(on_primary_container, "ff")
        ));
        content.push_str(&format!(
            "selection-match={}\n",
            hex_to_fuzzel(primary, "ff")
        ));
        content.push_str(&format!("counter={}\n", hex_to_fuzzel(outline, "ff")));
        content.push_str(&format!("border={}\n", hex_to_fuzzel(outline, "ff")));

        tokio::fs::write(&colors_file, content).await?;

        tracing::info!("[Fuzzel] Updated colors at {}", colors_file.display());

        Ok(())
    }

    async fn config_files(&self) -> Result<Vec<ConfigFileInfo>> {
        let config_dir =
            dirs::config_dir().ok_or(lmtt_core::Error::Config("No config dir".into()))?;

        let fuzzel_ini = config_dir.join("fuzzel").join("fuzzel.ini");

        // If no fuzzel.ini exists, return empty (user needs to create one)
        if !fuzzel_ini.exists() {
            return Ok(vec![]);
        }

        let content = tokio::fs::read_to_string(&fuzzel_ini).await?;
        let include_line = "include=~/.config/fuzzel/lmtt-colors.ini";
        let already_included = content.contains(include_line);

        Ok(vec![ConfigFileInfo {
            path: fuzzel_ini,
            include_line: include_line.to_string(),
            description: "Include lmtt colors into Fuzzel config".to_string(),
            already_included,
        }])
    }
}
