use crate::{ThemeModule, ConfigFileInfo};
use async_trait::async_trait;
use lmtt_core::{ColorScheme, Config, Result};

crate::register_module!(HyprlockModule);

pub struct HyprlockModule;

impl HyprlockModule {
    pub fn new() -> Self {
        Self
    }

    /// Convert hex color to RGB components
    fn hex_to_rgb(hex: &str) -> (u8, u8, u8) {
        let hex = hex.trim_start_matches('#');
        let r = u8::from_str_radix(&hex[0..2], 16).unwrap_or(0);
        let g = u8::from_str_radix(&hex[2..4], 16).unwrap_or(0);
        let b = u8::from_str_radix(&hex[4..6], 16).unwrap_or(0);
        (r, g, b)
    }
}

#[async_trait]
impl ThemeModule for HyprlockModule {
    fn name(&self) -> &'static str {
        "hyprlock"
    }

    fn binary_name(&self) -> &'static str {
        "hyprlock"
    }

    fn priority(&self) -> u8 {
        100
    }

    async fn apply(&self, scheme: &ColorScheme, _config: &Config) -> Result<()> {
        let colors_conf = dirs::config_dir()
            .ok_or(lmtt_core::Error::Config("No config dir".into()))?
            .join("hypr")
            .join("lmtt-hyprlock-colors.conf");

        // Ensure directory exists
        if let Some(parent) = colors_conf.parent() {
            tokio::fs::create_dir_all(parent).await?;
        }

        // Default colors
        let default_surface = "#12131a".to_string();
        let default_on_surface = "#e3e1ec".to_string();
        let default_primary = "#9fd491".to_string();
        let default_primary_container = "#1e3a1a".to_string();
        let default_error = "#ffb4ab".to_string();
        let default_secondary = "#c5c8b8".to_string();
        let default_surface_container = "#1e1f26".to_string();

        // Get colors from scheme
        let surface = scheme.get("surface").unwrap_or(&default_surface);
        let on_surface = scheme.get("on_surface").unwrap_or(&default_on_surface);
        let primary = scheme.get("primary").unwrap_or(&default_primary);
        let primary_container = scheme.get("primary_container").unwrap_or(&default_primary_container);
        let error = scheme.get("error").unwrap_or(&default_error);
        let secondary = scheme.get("secondary").unwrap_or(&default_secondary);
        let surface_container = scheme.get("surface_container").unwrap_or(&default_surface_container);

        // Generate content
        let mut content = String::new();
        content.push_str("# Generated by lmtt (Linux Matugen Theme Toggle)\n");
        content.push_str("# Material You colors for hyprlock\n");
        content.push_str(&format!("# Mode: {}\n\n", scheme.mode));

        // RGB format (without #)
        content.push_str(&format!("$surface = rgb({})\n", surface.trim_start_matches('#')));
        content.push_str(&format!("$on_surface = rgb({})\n", on_surface.trim_start_matches('#')));
        content.push_str(&format!("$primary = rgb({})\n", primary.trim_start_matches('#')));
        content.push_str(&format!("$primary_container = rgb({})\n", primary_container.trim_start_matches('#')));
        content.push_str(&format!("$error = rgb({})\n", error.trim_start_matches('#')));
        content.push_str(&format!("$secondary = rgb({})\n", secondary.trim_start_matches('#')));
        content.push_str(&format!("$surface_container = rgb({})\n", surface_container.trim_start_matches('#')));
        content.push_str("\n");

        // RGBA versions for backgrounds with transparency
        let (sr, sg, sb) = Self::hex_to_rgb(surface);
        let (pr, pg, pb) = Self::hex_to_rgb(primary);
        let (scr, scg, scb) = Self::hex_to_rgb(surface_container);

        content.push_str("# RGBA versions for backgrounds\n");
        content.push_str(&format!("$surface_rgba = rgba({}, {}, {}, 1.0)\n", sr, sg, sb));
        content.push_str(&format!("$primary_rgba = rgba({}, {}, {}, 1.0)\n", pr, pg, pb));
        content.push_str(&format!("$surface_dim_rgba = rgba({}, {}, {}, 0.7)\n", scr, scg, scb));
        content.push_str(&format!("$surface_container_rgba = rgba({}, {}, {}, 0.85)\n", scr, scg, scb));

        tokio::fs::write(&colors_conf, content).await?;

        tracing::info!("[Hyprlock] Updated colors at {}", colors_conf.display());

        Ok(())
    }

    async fn config_files(&self) -> Result<Vec<ConfigFileInfo>> {
        let config_dir = dirs::config_dir()
            .ok_or(lmtt_core::Error::Config("No config dir".into()))?;

        let hyprlock_conf = config_dir.join("hypr").join("hyprlock.conf");

        if !hyprlock_conf.exists() {
            return Ok(vec![]);
        }

        // Check if already included
        let content = tokio::fs::read_to_string(&hyprlock_conf).await?;
        let include_line = "source = ~/.config/hypr/lmtt-hyprlock-colors.conf";
        let already_included = content.contains(include_line);

        Ok(vec![ConfigFileInfo {
            path: hyprlock_conf,
            include_line: include_line.to_string(),
            description: "Source lmtt colors in Hyprlock config".to_string(),
            already_included,
        }])
    }
}
