use crate::{ThemeModule, ConfigFileInfo};
use async_trait::async_trait;
use lmtt_core::{ColorScheme, Config, Result};

crate::register_module!(HyprlandModule);

pub struct HyprlandModule;

impl Default for HyprlandModule {
    fn default() -> Self {
        Self::new()
    }
}

impl HyprlandModule {
    pub fn new() -> Self {
        Self
    }
}

/// Whether the user runs with misc:disable_autoreload = 1. Defaults to false
/// (autoreload on) when hyprctl can't be queried.
async fn autoreload_disabled() -> bool {
    let Ok(output) = tokio::process::Command::new("hyprctl")
        .args(["getoption", "misc:disable_autoreload", "-j"])
        .output()
        .await
    else {
        return false;
    };
    if !output.status.success() {
        return false;
    }
    serde_json::from_slice::<serde_json::Value>(&output.stdout)
        .ok()
        .and_then(|v| v.get("int").and_then(|i| i.as_i64()))
        .map(|i| i == 1)
        .unwrap_or(false)
}

/// Hyprland's rgb() takes exactly 6 hex digits. Parse via hex_to_rgb (handles
/// #rgb / #rrggbb / #rrggbbaa and is byte-safe) and re-emit canonical rrggbb.
fn hypr_rgb(hex: &str) -> String {
    match lmtt_core::colors::hex_to_rgb(hex) {
        Ok((r, g, b)) => format!("{:02x}{:02x}{:02x}", r, g, b),
        Err(_) => "000000".to_string(),
    }
}

#[async_trait]
impl ThemeModule for HyprlandModule {
    fn name(&self) -> &'static str {
        "hyprland"
    }
    
    fn binary_name(&self) -> &'static str {
        "hyprctl"
    }
    
    fn priority(&self) -> u8 {
        100
    }

    fn legacy_include_lines(&self) -> Vec<String> {
        // Pre-rename artifact: older lmtt wrote ~/.config/hypr/colors.conf and
        // injected this source line. On re-setup its block is stripped so the
        // upgrade doesn't leave hyprland sourcing a file we no longer write.
        vec!["source = ~/.config/hypr/colors.conf".to_string()]
    }
    
    async fn apply(&self, scheme: &ColorScheme, _config: &Config) -> Result<()> {
        let hypr_dir = dirs::config_dir()
            .ok_or(lmtt_core::Error::Config("No config dir".into()))?
            .join("hypr");
        let colors_conf = hypr_dir.join("lmtt-colors.conf");

        tokio::fs::create_dir_all(&hypr_dir).await?;

        let primary = hypr_rgb(&scheme.get_or_fallback("primary"));
        let secondary = hypr_rgb(&scheme.get_or_fallback("secondary"));
        let outline = hypr_rgb(&scheme.get_or_fallback("outline"));
        let surface = hypr_rgb(&scheme.get_or_fallback("surface"));
        let on_surface = hypr_rgb(&scheme.get_or_fallback("on_surface"));

        let mut content = String::new();
        content.push_str("# Generated by lmtt (Linux Multi-Theme Toggle)\n");
        content.push_str("# Material You color variables for Hyprland\n");
        content.push_str(&format!("# Mode: {}\n", scheme.mode));
        content.push_str("# Reference these in your Hyprland config, e.g.\n");
        content.push_str("#   general:col.active_border = $lmtt_active_border\n");
        content.push_str("#   general:col.inactive_border = $lmtt_inactive_border\n\n");
        content.push_str(&format!("$lmtt_primary = rgb({})\n", primary));
        content.push_str(&format!("$lmtt_secondary = rgb({})\n", secondary));
        content.push_str(&format!("$lmtt_outline = rgb({})\n", outline));
        content.push_str(&format!("$lmtt_surface = rgb({})\n", surface));
        content.push_str(&format!("$lmtt_on_surface = rgb({})\n", on_surface));
        content.push_str(&format!("$lmtt_active_border = rgb({}) rgb({}) 45deg\n", primary, secondary));
        content.push_str(&format!("$lmtt_inactive_border = rgb({})\n", outline));
        content.push_str("$lmtt_shadow = rgb(000000)\n");

        lmtt_core::fsutil::write_atomic(&colors_conf, content).await?;

        tracing::info!("[Hyprland] Updated colors at {}", colors_conf.display());

        // With autoreload on (the default), the write above already triggers
        // exactly one config reload. `hyprctl reload` forces a FULL reparse
        // including monitor re-application — on HDR/multi-head setups that
        // stalls the compositor for seconds — so only reload explicitly when
        // the user has disabled autoreload.
        if autoreload_disabled().await {
            let reload = tokio::process::Command::new("hyprctl")
                .arg("reload")
                .output()
                .await;
            match reload {
                Ok(output) if !output.status.success() => {
                    tracing::warn!(
                        "[Hyprland] hyprctl reload failed: {}",
                        String::from_utf8_lossy(&output.stderr).trim()
                    );
                }
                Err(e) => tracing::warn!("[Hyprland] hyprctl reload failed to run: {}", e),
                _ => {}
            }
        }

        Ok(())
    }

    async fn config_files(&self) -> Result<Vec<ConfigFileInfo>> {
        let config_dir = dirs::config_dir()
            .ok_or(lmtt_core::Error::Config("No config dir".into()))?;

        let hyprland_conf = config_dir.join("hypr").join("hyprland.conf");

        if !hyprland_conf.exists() {
            return Ok(vec![]);
        }

        // Check if already included
        let content = tokio::fs::read_to_string(&hyprland_conf).await?;
        let include_line = "source = ~/.config/hypr/lmtt-colors.conf";
        // The include often lives in a sourced sub-config rather than
        // hyprland.conf itself — any lmtt-colors.conf reference counts.
        let already_included = crate::is_included(&content, "lmtt-colors.conf");

        Ok(vec![ConfigFileInfo {
            path: hyprland_conf,
            include_line: include_line.to_string(),
            description: "Source lmtt colors in Hyprland config".to_string(),
            already_included,
        }])
    }
}
