use crate::{gtk, ConfigFileInfo, ThemeModule};
use async_trait::async_trait;
use lmtt_core::{colors::hex_to_rgb, ColorScheme, Config, Result};
use std::path::PathBuf;

crate::register_module!(QtModule);

pub struct QtModule;

impl Default for QtModule {
    fn default() -> Self {
        Self::new()
    }
}

impl QtModule {
    pub fn new() -> Self {
        Self
    }
}

/// QPalette ColorRole order used by qt6ct (22 roles through Accent).
const PALETTE_KEYS: [&str; 22] = [
    "on_surface",                // WindowText
    "surface_container",         // Button
    "surface_container_highest", // Light
    "surface_container_high",    // Midlight
    "outline",                   // Dark
    "outline_variant",           // Mid
    "on_surface",                // Text
    "on_primary",                // BrightText
    "on_surface",                // ButtonText
    "surface",                   // Base
    "surface",                   // Window
    "shadow",                    // Shadow
    "primary",                   // Highlight
    "on_primary",                // HighlightedText
    "primary",                   // Link
    "secondary",                 // LinkVisited
    "surface_container_low",     // AlternateBase
    "surface",                   // NoRole
    "inverse_surface",           // ToolTipBase
    "inverse_on_surface",        // ToolTipText
    "outline",                   // PlaceholderText
    "primary",                   // Accent
];

fn qt_hex(scheme: &ColorScheme, key: &str) -> String {
    let raw = scheme.get_or_fallback(key);
    match hex_to_rgb(&raw) {
        Ok((r, g, b)) => format!("#{:02x}{:02x}{:02x}", r, g, b),
        Err(_) => "#808080".to_string(),
    }
}

fn palette_csv(scheme: &ColorScheme) -> String {
    PALETTE_KEYS
        .iter()
        .map(|key| qt_hex(scheme, key))
        .collect::<Vec<_>>()
        .join(", ")
}

fn color_scheme_file(scheme: &ColorScheme) -> String {
    let csv = palette_csv(scheme);
    format!(
        "# generated by lmtt — do not edit\n\
         # Mode: {}\n\
         [ColorScheme]\n\
         active_colors={csv}\n\
         disabled_colors={csv}\n\
         inactive_colors={csv}\n",
        scheme.mode
    )
}

fn qt6ct_dir() -> Result<PathBuf> {
    let config_dir =
        dirs::config_dir().ok_or_else(|| lmtt_core::Error::Config("No config dir".into()))?;
    Ok(config_dir.join("qt6ct"))
}

async fn current_icon_theme() -> String {
    let output = tokio::process::Command::new("gsettings")
        .args(["get", "org.gnome.desktop.interface", "icon-theme"])
        .output()
        .await;
    match output {
        Ok(o) if o.status.success() => String::from_utf8_lossy(&o.stdout)
            .trim()
            .trim_matches('\'')
            .to_string(),
        _ => "Adwaita".to_string(),
    }
}

async fn platform_theme_is_qt6ct() -> bool {
    if let Ok(val) = std::env::var("QT_QPA_PLATFORMTHEME") {
        return val == "qt6ct";
    }
    session_env_has_platformtheme_value("qt6ct").await
}

async fn session_env_has_any_platformtheme() -> bool {
    let Ok(output) = tokio::process::Command::new("systemctl")
        .args(["--user", "show-environment"])
        .output()
        .await
    else {
        return false;
    };
    output.status.success()
        && String::from_utf8_lossy(&output.stdout)
            .lines()
            .any(|line| line.starts_with("QT_QPA_PLATFORMTHEME="))
}

async fn session_env_has_platformtheme_value(want: &str) -> bool {
    let Ok(output) = tokio::process::Command::new("systemctl")
        .args(["--user", "show-environment"])
        .output()
        .await
    else {
        return false;
    };
    if !output.status.success() {
        return false;
    }
    String::from_utf8_lossy(&output.stdout)
        .lines()
        .any(|line| line == format!("QT_QPA_PLATFORMTHEME={want}"))
}

#[async_trait]
impl ThemeModule for QtModule {
    fn name(&self) -> &'static str {
        "qt"
    }

    fn binary_name(&self) -> &'static str {
        "qt6ct"
    }

    fn priority(&self) -> u8 {
        20
    }

    async fn apply(&self, scheme: &ColorScheme, _config: &Config) -> Result<()> {
        let dir = qt6ct_dir()?;
        let colors_dir = dir.join("colors");
        tokio::fs::create_dir_all(&colors_dir).await?;

        let colors_path = colors_dir.join("lmtt.conf");
        lmtt_core::fsutil::write_atomic(&colors_path, color_scheme_file(scheme)).await?;

        // kvantum/qt5ct users win if they already set a platform theme that
        // is not qt6ct. hypr-DE's uwsm env sets qt6ct, so the common path
        // merges Appearance and leaves Fonts/Interface alone.
        let already_set = std::env::var("QT_QPA_PLATFORMTHEME").is_ok()
            || session_env_has_any_platformtheme().await;
        if !already_set {
            let env_commands = vec![
                (
                    "systemctl",
                    vec!["--user", "set-environment", "QT_QPA_PLATFORMTHEME=qt6ct"],
                ),
                (
                    "dbus-update-activation-environment",
                    vec!["--systemd", "QT_QPA_PLATFORMTHEME=qt6ct"],
                ),
            ];

            for (cmd, args) in env_commands {
                if which::which(cmd).is_err() {
                    continue;
                }
                let result = tokio::process::Command::new(cmd).args(&args).output().await;
                match result {
                    Ok(output) if !output.status.success() => {
                        tracing::warn!(
                            "[Qt] {} failed: {}",
                            cmd,
                            String::from_utf8_lossy(&output.stderr).trim()
                        );
                    }
                    Err(e) => tracing::warn!("[Qt] {} failed to run: {}", cmd, e),
                    _ => {}
                }
            }

            if which::which("hyprctl").is_ok() {
                let _ = tokio::process::Command::new("hyprctl")
                    .args(["setenv", "QT_QPA_PLATFORMTHEME", "qt6ct"])
                    .output()
                    .await;
            }
            tracing::info!("[Qt] Exported QT_QPA_PLATFORMTHEME=qt6ct for new processes");
        } else {
            tracing::debug!("[Qt] QT_QPA_PLATFORMTHEME already set, leaving session env alone");
        }

        if platform_theme_is_qt6ct().await || !already_set {
            let conf_path = dir.join("qt6ct.conf");
            let current = tokio::fs::read_to_string(&conf_path)
                .await
                .unwrap_or_default();
            let icon_theme = current_icon_theme().await;
            let updates = [
                (
                    "color_scheme_path",
                    colors_path.to_string_lossy().into_owned(),
                ),
                ("custom_palette", "true".to_string()),
                ("style", "Fusion".to_string()),
                ("icon_theme", icon_theme),
            ];
            let merged = gtk::merge_ini(&current, "Appearance", &updates);
            lmtt_core::fsutil::write_atomic(&conf_path, merged).await?;
            tracing::info!(
                "[Qt] Wrote {} palette and merged qt6ct Appearance",
                scheme.mode
            );
        }

        Ok(())
    }

    async fn config_files(&self) -> Result<Vec<ConfigFileInfo>> {
        let conf = qt6ct_dir()?.join("qt6ct.conf");
        Ok(vec![ConfigFileInfo {
            path: conf,
            include_line: String::new(),
            description: "LMTT writes [Appearance] (palette path, Fusion, icons); Fonts stay yours"
                .to_string(),
            already_included: true,
        }])
    }
}

#[cfg(test)]
mod tests {
    use super::{color_scheme_file, palette_csv, PALETTE_KEYS};
    use lmtt_core::{ColorScheme, ThemeMode};

    fn scheme() -> ColorScheme {
        let mut s = ColorScheme::new(ThemeMode::Dark);
        s.set("primary".into(), "#ffb77a".into());
        s.set("on_primary".into(), "#19120c".into());
        s.set("surface".into(), "#19120c".into());
        s.set("on_surface".into(), "#efe0d6".into());
        s
    }

    #[test]
    fn palette_has_22_roles() {
        assert_eq!(PALETTE_KEYS.len(), 22);
        let csv = palette_csv(&scheme());
        assert_eq!(csv.split(", ").count(), 22);
        assert!(csv.contains("#ffb77a"));
        assert!(csv.contains("#19120c"));
        assert!(!csv.contains("rgb("));
    }

    #[test]
    fn color_file_is_qt6ct_ini() {
        let body = color_scheme_file(&scheme());
        assert!(body.contains("[ColorScheme]"));
        assert!(body.contains("active_colors="));
        assert!(body.contains("generated by lmtt"));
    }

    #[test]
    fn appearance_merge_leaves_fonts() {
        let existing = "[Appearance]\nstyle = Windows\n\n[Fonts]\nfixed = \"Noto Sans Mono,10\"\n";
        let merged = crate::gtk::merge_ini(
            existing,
            "Appearance",
            &[
                ("style", "Fusion".to_string()),
                ("custom_palette", "true".to_string()),
            ],
        );
        assert!(merged.contains("style = Fusion"));
        assert!(merged.contains("custom_palette = true"));
        assert!(merged.contains("fixed = \"Noto Sans Mono,10\""));
        assert!(!merged.contains("Windows"));
    }
}
