use crate::ThemeModule;
use async_trait::async_trait;
use lmtt_core::{ColorScheme, Config, Result, ThemeMode};

crate::register_module!(RegreetModule);

pub struct RegreetModule;

impl RegreetModule {
    pub fn new() -> Self {
        Self
    }

    /// Convert hex color to RGB components
    fn hex_to_rgb(hex: &str) -> (u8, u8, u8) {
        let hex = hex.trim_start_matches('#');
        let r = u8::from_str_radix(&hex[0..2], 16).unwrap_or(0);
        let g = u8::from_str_radix(&hex[2..4], 16).unwrap_or(0);
        let b = u8::from_str_radix(&hex[4..6], 16).unwrap_or(0);
        (r, g, b)
    }

    /// Format as CSS rgba with alpha
    fn to_rgba(hex: &str, alpha: f32) -> String {
        let (r, g, b) = Self::hex_to_rgb(hex);
        format!("rgba({}, {}, {}, {:.2})", r, g, b, alpha)
    }
}

#[async_trait]
impl ThemeModule for RegreetModule {
    fn name(&self) -> &'static str {
        "regreet"
    }

    fn binary_name(&self) -> &'static str {
        "regreet"
    }

    fn priority(&self) -> u8 {
        100
    }

    async fn apply(&self, scheme: &ColorScheme, config: &Config) -> Result<()> {
        let lmtt_dir = dirs::config_dir()
            .ok_or(lmtt_core::Error::Config("No config dir".into()))?
            .join("lmtt");

        // Ensure directory exists
        tokio::fs::create_dir_all(&lmtt_dir).await?;

        let css_path = lmtt_dir.join("regreet.css");

        // Default colors based on mode
        let (default_surface, default_on_surface, default_primary, default_error, default_surface_container) =
            if scheme.mode == ThemeMode::Dark {
                ("#12131a", "#e3e1ec", "#9fd491", "#ffb4ab", "#1e1f26")
            } else {
                ("#fbf8ff", "#1a1b23", "#2d6a2f", "#ba1a1a", "#eef0e5")
            };

        // Get colors from scheme
        let surface = scheme.get("surface").map(|s| s.as_str()).unwrap_or(default_surface);
        let on_surface = scheme.get("on_surface").map(|s| s.as_str()).unwrap_or(default_on_surface);
        let primary = scheme.get("primary").map(|s| s.as_str()).unwrap_or(default_primary);
        let error = scheme.get("error").map(|s| s.as_str()).unwrap_or(default_error);
        let surface_container = scheme.get("surface_container").map(|s| s.as_str()).unwrap_or(default_surface_container);

        // Generate CSS
        let mut css = String::new();
        css.push_str("/* Generated by lmtt (Linux Matugen Theme Toggle) */\n");
        css.push_str(&format!("/* Mode: {} */\n\n", scheme.mode));

        // Transparent window background (swaybg handles wallpaper)
        css.push_str("window {\n");
        css.push_str("    background-color: transparent;\n");
        css.push_str("}\n\n");

        // Semi-transparent background for main login container
        css.push_str("frame.background {\n");
        css.push_str(&format!("    background-color: {};\n", Self::to_rgba(surface, 0.75)));
        css.push_str("    border-radius: 16px;\n");
        css.push_str("    padding: 24px;\n");
        css.push_str("}\n\n");

        // Label styling with text shadow for legibility
        css.push_str("label {\n");
        css.push_str(&format!("    color: {};\n", on_surface));
        css.push_str("    text-shadow: 0 1px 3px rgba(0, 0, 0, 0.4);\n");
        css.push_str("}\n\n");

        // Entry fields (password, username)
        css.push_str("entry {\n");
        css.push_str(&format!("    background-color: {};\n", Self::to_rgba(surface_container, 0.6)));
        css.push_str("    border-radius: 8px;\n");
        css.push_str(&format!("    color: {};\n", on_surface));
        css.push_str("    padding: 8px 12px;\n");
        css.push_str("}\n\n");

        css.push_str("entry:focus {\n");
        css.push_str(&format!("    background-color: {};\n", Self::to_rgba(surface_container, 0.8)));
        css.push_str(&format!("    outline: 2px solid {};\n", Self::to_rgba(primary, 0.6)));
        css.push_str("}\n\n");

        // Dropdown selectors
        css.push_str("dropdown, combobox {\n");
        css.push_str(&format!("    background-color: {};\n", Self::to_rgba(surface_container, 0.6)));
        css.push_str("    border-radius: 8px;\n");
        css.push_str(&format!("    color: {};\n", on_surface));
        css.push_str("}\n\n");

        // Login button
        css.push_str("button.suggested-action {\n");
        css.push_str(&format!("    background-color: {};\n", Self::to_rgba(primary, 0.85)));
        css.push_str("    border-radius: 8px;\n");
        css.push_str("    color: white;\n");
        css.push_str("    padding: 8px 16px;\n");
        css.push_str("}\n\n");

        css.push_str("button.suggested-action:hover {\n");
        css.push_str(&format!("    background-color: {};\n", primary));
        css.push_str("}\n\n");

        // Power/Reboot buttons
        css.push_str("button.destructive-action {\n");
        css.push_str(&format!("    background-color: {};\n", Self::to_rgba(error, 0.7)));
        css.push_str("    border-radius: 8px;\n");
        css.push_str("}\n\n");

        css.push_str("button.destructive-action:hover {\n");
        css.push_str(&format!("    background-color: {};\n", Self::to_rgba(error, 0.9)));
        css.push_str("}\n");

        tokio::fs::write(&css_path, css).await?;

        tracing::info!("[Regreet] Updated CSS at {}", css_path.display());

        // Run post-command if configured (for syncing to /etc/greetd/)
        if let Some(cmd) = config.module_command("regreet") {
            tracing::debug!("[Regreet] Running post-command: {}", cmd);
            let output = tokio::process::Command::new("sh")
                .arg("-c")
                .arg(cmd)
                .output()
                .await;

            match output {
                Ok(out) if out.status.success() => {
                    tracing::info!("[Regreet] Post-command succeeded");
                }
                Ok(out) => {
                    let stderr = String::from_utf8_lossy(&out.stderr);
                    tracing::warn!("[Regreet] Post-command failed: {}", stderr);
                }
                Err(e) => {
                    tracing::warn!("[Regreet] Failed to run post-command: {}", e);
                }
            }
        }

        Ok(())
    }
}
