use crate::{ThemeModule, ConfigFileInfo};
use async_trait::async_trait;
use lmtt_core::{ColorScheme, Config, Result};

crate::register_module!(SwayNCModule);

pub struct SwayNCModule;

impl Default for SwayNCModule {
    fn default() -> Self {
        Self::new()
    }
}

impl SwayNCModule {
    pub fn new() -> Self {
        Self
    }
}

/// Build a self-contained color sheet for swaync. Three layers are needed:
///
/// 1. All Material You tokens as @define-color, so the user's style.css can
///    reference @background/@primary/... with a single local import.
/// 2. swaync's legacy @define-color slot names (older themes).
/// 3. A `:root` block overriding the CSS custom properties that swaync
///    0.11+'s DEFAULT stylesheet uses (var(--text-color) etc.). swaync loads
///    its default sheet underneath the user's — anything the user doesn't
///    explicitly style renders with these variables, and the shipped values
///    are dark-theme (white text), which is unreadable in light mode.
///    Custom properties need literal values here, not @-color references.
fn build_swaync_css(scheme: &ColorScheme) -> Result<String> {
    let get = |key: &str| scheme.get_or_fallback(key);
    let surface = get("surface");
    let (r, g, b) = lmtt_core::colors::hex_to_rgb(&surface)
        .map_err(lmtt_core::Error::Module)?;

    let mut css = String::from("/* SwayNC colors generated by lmtt */\n");
    css.push_str(&format!("/* Mode: {} */\n\n", scheme.mode));
    css.push_str(&scheme.to_gtk_css());

    css.push_str("\n/* swaync named color slots */\n");
    for (slot, token) in [
        ("cc-bg", "surface"),
        ("noti-bg", "surface"),
        ("noti-bg-opaque", "surface"),
        ("noti-bg-darker", "surface_container_low"),
        ("noti-bg-hover", "surface_container_high"),
        ("noti-bg-hover-opaque", "surface_container_high"),
        ("noti-bg-focus", "surface_container_highest"),
        ("noti-close-bg", "error"),
        ("noti-close-bg-hover", "error"),
        ("text-color", "on_surface"),
        ("text-color-disabled", "on_surface_variant"),
        ("bg-selected", "primary"),
        ("on-primary", "on_primary"),
        ("on-error", "on_error"),
        ("surface-container", "surface_container"),
    ] {
        css.push_str(&format!("@define-color {} {};\n", slot, get(token)));
    }
    css.push_str("@define-color noti-border-color transparent;\n");

    css.push_str("\n/* swaync >= 0.11 default-stylesheet variables */\n:root {\n");
    css.push_str(&format!("  --cc-bg: {};\n", surface));
    css.push_str(&format!("  --noti-bg: {}, {}, {};\n", r, g, b));
    css.push_str("  --noti-bg-alpha: 1;\n");
    css.push_str(&format!("  --noti-bg-darker: {};\n", get("surface_container_low")));
    css.push_str(&format!("  --noti-bg-hover: {};\n", get("surface_container_high")));
    css.push_str(&format!("  --noti-bg-focus: {};\n", get("surface_container_highest")));
    css.push_str(&format!("  --noti-close-bg: {};\n", get("error")));
    css.push_str(&format!("  --noti-close-bg-hover: {};\n", get("error")));
    css.push_str(&format!("  --noti-border-color: {};\n", get("outline_variant")));
    css.push_str(&format!("  --text-color: {};\n", get("on_surface")));
    css.push_str(&format!("  --text-color-disabled: {};\n", get("on_surface_variant")));
    css.push_str(&format!("  --bg-selected: {};\n", get("primary")));
    // The mpris overlay sits on arbitrary album art and stays dark in both
    // modes; text over it must therefore stay light (styled in style.css).
    css.push_str("  --mpris-album-art-overlay: rgba(0, 0, 0, 0.6);\n");
    css.push_str("}\n");

    Ok(css)
}

#[async_trait]
impl ThemeModule for SwayNCModule {
    fn name(&self) -> &'static str {
        "swaync"
    }

    fn binary_name(&self) -> &'static str {
        "swaync"
    }

    /// Reload modules run after writer modules of lower priority; the shared
    /// palette itself is written by main before any module runs.
    fn priority(&self) -> u8 {
        150
    }

    async fn apply(&self, scheme: &ColorScheme, _config: &Config) -> Result<()> {
        let swaync_dir = dirs::config_dir()
            .ok_or(lmtt_core::Error::Config("No config dir".into()))?
            .join("swaync");
        let style_css = swaync_dir.join("style.css");

        // Only maintain the color file when style.css imports lmtt-colors.css
        // (any spelling: quoted, unquoted, or absolute path — must match what
        // config_files() considers "already configured", or setup reports it
        // configured while apply never writes the imported file). A style.css
        // that handles colors on its own needs no extra file.
        let style_content = tokio::fs::read_to_string(&style_css).await.unwrap_or_default();
        let uses_color_file = style_content.contains("lmtt-colors.css");

        if uses_color_file {
            let colors_file = swaync_dir.join("lmtt-colors.css");
            let css = build_swaync_css(scheme)?;
            let current = tokio::fs::read_to_string(&colors_file).await.unwrap_or_default();
            if current != css {
                lmtt_core::fsutil::write_atomic(&colors_file, css).await?;
                tracing::info!("[SwayNC] Updated colors at {}", colors_file.display());
            }
        }

        // Reload only if swaync is actually running. It's often installed as a
        // dependency while the user runs a different daemon (dunst/hyprpanel);
        // erroring on an unreachable daemon would fail this module — and pop a
        // FAILED notification — on every single switch.
        let running = tokio::process::Command::new("pgrep")
            .args(["-x", "swaync"])
            .output()
            .await
            .map(|o| o.status.success())
            .unwrap_or(false);
        if !running {
            tracing::debug!("[SwayNC] Not running; wrote colors, skipping reload");
            return Ok(());
        }

        for arg in ["--reload-config", "--reload-css"] {
            let output = tokio::process::Command::new("swaync-client")
                .arg(arg)
                .output()
                .await
                .map_err(|e| lmtt_core::Error::Module(format!("swaync-client failed to run: {}", e)))?;
            if !output.status.success() {
                let stderr = String::from_utf8_lossy(&output.stderr);
                return Err(lmtt_core::Error::Module(format!(
                    "swaync-client {} failed: {}", arg, stderr.trim()
                )));
            }
        }

        tracing::info!("[SwayNC] Reloaded");
        Ok(())
    }

    async fn config_files(&self) -> Result<Vec<ConfigFileInfo>> {
        let style_css = dirs::config_dir()
            .ok_or(lmtt_core::Error::Config("No config dir".into()))?
            .join("swaync")
            .join("style.css");

        if !style_css.exists() {
            return Ok(vec![]);
        }

        let content = tokio::fs::read_to_string(&style_css).await.unwrap_or_default();
        let include_line = "@import url('lmtt-colors.css');";

        // Any reference to the palette counts as configured — a style.css
        // that imports ~/.config/matugen/lmtt-colors.css directly (absolute
        // or relative) must not be offered a second, redundant import.
        let already_included = crate::is_included(&content, "lmtt-colors.css");

        Ok(vec![ConfigFileInfo {
            path: style_css,
            include_line: include_line.to_string(),
            description: "Import lmtt colors into SwayNC CSS".to_string(),
            already_included,
        }])
    }
}
