use crate::{ThemeModule, ConfigFileInfo};
use async_trait::async_trait;
use lmtt_core::{ColorScheme, Config, Result};

crate::register_module!(TmuxModule);

pub struct TmuxModule;

impl Default for TmuxModule {
    fn default() -> Self {
        Self::new()
    }
}

impl TmuxModule {
    pub fn new() -> Self {
        Self
    }
}

#[async_trait]
impl ThemeModule for TmuxModule {
    fn name(&self) -> &'static str {
        "tmux"
    }

    fn binary_name(&self) -> &'static str {
        "tmux"
    }

    async fn apply(&self, scheme: &ColorScheme, _config: &Config) -> Result<()> {
        let colors_conf = dirs::config_dir()
            .ok_or(lmtt_core::Error::Config("No config dir".into()))?
            .join("tmux")
            .join("lmtt-colors.conf");

        if let Some(parent) = colors_conf.parent() {
            tokio::fs::create_dir_all(parent).await?;
        }

        let primary = scheme.get_or_fallback("primary");
        let on_primary = scheme.get_or_fallback("on_primary");
        let surface = scheme.get_or_fallback("surface");
        let on_surface = scheme.get_or_fallback("on_surface");
        let outline_variant = scheme.get_or_fallback("outline_variant");

        let mut content = String::new();
        content.push_str("# Tmux colors generated by lmtt\n\n");
        content.push_str(&format!("set -g status-style 'bg={} fg={}'\n", surface, on_surface));
        content.push_str(&format!("set -g pane-active-border-style 'fg={}'\n", primary));
        // outline_variant, not surface: a border the color of the background
        // is invisible
        content.push_str(&format!("set -g pane-border-style 'fg={}'\n", outline_variant));
        content.push_str(&format!("set -g message-style 'bg={} fg={}'\n", primary, on_primary));

        lmtt_core::fsutil::write_atomic(&colors_conf, content).await?;

        tracing::info!("[Tmux] Updated colors at {}", colors_conf.display());

        // Re-source into a running server so attached sessions update live.
        // "no server running" is normal — only log real failures.
        let reload = tokio::process::Command::new("tmux")
            .args(["source-file", &colors_conf.to_string_lossy()])
            .output()
            .await;
        match reload {
            Ok(output) if output.status.success() => {
                tracing::info!("[Tmux] Reloaded running sessions");
            }
            Ok(output) => {
                let stderr = String::from_utf8_lossy(&output.stderr);
                // tmux reports an absent server as either "no server running"
                // or "error connecting to <socket>" depending on version
                if stderr.contains("no server") || stderr.contains("error connecting") {
                    tracing::debug!("[Tmux] No running server to reload");
                } else {
                    tracing::warn!("[Tmux] source-file failed: {}", stderr.trim());
                }
            }
            Err(e) => tracing::warn!("[Tmux] Failed to run tmux: {}", e),
        }

        Ok(())
    }

    async fn config_files(&self) -> Result<Vec<ConfigFileInfo>> {
        let home = dirs::home_dir()
            .ok_or(lmtt_core::Error::Config("No home dir".into()))?;
        let config_dir = dirs::config_dir()
            .ok_or(lmtt_core::Error::Config("No config dir".into()))?;

        // tmux >= 3.1 reads ~/.config/tmux/tmux.conf; check it before the
        // legacy dotfile so XDG users get setup support too.
        let candidates = [
            config_dir.join("tmux").join("tmux.conf"),
            home.join(".tmux.conf"),
        ];
        let Some(tmux_conf) = candidates.into_iter().find(|p| p.exists()) else {
            return Ok(vec![]);
        };

        let content = tokio::fs::read_to_string(&tmux_conf).await?;
        let include_line = "source-file ~/.config/tmux/lmtt-colors.conf";
        let already_included = crate::is_included(&content, include_line);

        Ok(vec![ConfigFileInfo {
            path: tmux_conf,
            include_line: include_line.to_string(),
            description: "Source lmtt colors in tmux config".to_string(),
            already_included,
        }])
    }
}
