use crate::{ThemeModule, ConfigFileInfo};
use async_trait::async_trait;
use lmtt_core::{ColorScheme, Config, Result};

pub struct TmuxModule;

impl TmuxModule {
    pub fn new() -> Self {
        Self
    }
}

#[async_trait]
impl ThemeModule for TmuxModule {
    fn name(&self) -> &'static str {
        "tmux"
    }
    
    fn binary_name(&self) -> &'static str {
        "tmux"
    }
    
    async fn apply(&self, scheme: &ColorScheme, _config: &Config) -> Result<()> {
        let colors_conf = dirs::config_dir()
            .ok_or(lmtt_core::Error::Config("No config dir".into()))?
            .join("tmux")
            .join("lmtt-colors.conf");
        
        if let Some(parent) = colors_conf.parent() {
            tokio::fs::create_dir_all(parent).await?;
        }
        
        // Extract key colors
        let default_primary = "#9fd491".to_string();
        let default_surface = "#12131a".to_string();
        let default_on_surface = "#e3e1ec".to_string();
        
        let primary = scheme.get("primary").unwrap_or(&default_primary);
        let surface = scheme.get("surface").unwrap_or(&default_surface);
        let on_surface = scheme.get("on_surface").unwrap_or(&default_on_surface);
        
        let mut content = String::new();
        content.push_str("# Tmux colors generated by lmtt\n\n");
        content.push_str(&format!("set -g status-style 'bg={} fg={}'\n", surface, on_surface));
        content.push_str(&format!("set -g pane-active-border-style 'fg={}'\n", primary));
        content.push_str(&format!("set -g pane-border-style 'fg={}'\n", surface));
        content.push_str(&format!("set -g message-style 'bg={} fg={}'\n", primary, surface));
        
        tokio::fs::write(&colors_conf, content).await?;
        
        tracing::info!("[Tmux] Updated colors at {}", colors_conf.display());
        
        Ok(())
    }
    
    async fn config_files(&self) -> Result<Vec<ConfigFileInfo>> {
        let config_dir = dirs::home_dir()
            .ok_or(lmtt_core::Error::Config("No home dir".into()))?;
        
        let tmux_conf = config_dir.join(".tmux.conf");
        
        if !tmux_conf.exists() {
            return Ok(vec![]);
        }
        
        let content = tokio::fs::read_to_string(&tmux_conf).await?;
        let include_line = "source-file ~/.config/tmux/lmtt-colors.conf";
        let already_included = content.contains(include_line);
        
        Ok(vec![ConfigFileInfo {
            path: tmux_conf,
            include_line: include_line.to_string(),
            description: "Source lmtt colors in tmux config".to_string(),
            already_included,
        }])
    }
}
