name: Release

on:
  push:
    tags: ['v*']

permissions:
  contents: write

jobs:
  release:
    uses: MasonRhodesDev/packaging-workflows/.github/workflows/release.yml@d43d3b4a06664363f1a3cd1ee7ee467b0b066ec6
    secrets: inherit
    with:
      spec-name: lmtt
      security: true
